### PR TITLE
fix: fix Position type error

### PR DESCRIPTION
**Pull request by kitety**
fix Position type error

### CODE REVIEW

**Comment by jaywcjlove** [comment]
@kitety Upgrade `+ @uiw/react-codemirror@3.0.3`

**Comment by jaywcjlove** [comment]
@kitety thx!

**Comment by kitety** [comment]
Would you mind  tell me when to publish the latest to npm? I want to use it .

**Comment by jaywcjlove** [comment]
@kitety Has been released.  https://www.npmjs.com/package/@uiw/react-codemirror/v/3.0.3

**Pull request merged**
